name = "openai-api-worker"
main = "src/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[env.development]
name = "openai-api-worker-dev"

[env.staging]
name = "openai-api-worker-staging"
route = "api-staging.wemake.cx/v1/*"

[env.production]
name = "openai-api-worker-prod"
route = "api.wemake.cx/v1/*"

# Development environment configuration
[[env.development.d1_databases]]
binding = "DB"
database_name = "openai-api-dev"
database_id = "your-dev-d1-database-id"

[[env.development.kv_namespaces]]
binding = "CACHE"
id = "your-dev-kv-namespace-id"
preview_id = "your-dev-kv-preview-id"

[[env.development.kv_namespaces]]
binding = "RATE_LIMIT"
id = "your-dev-rate-limit-kv-id"
preview_id = "your-dev-rate-limit-preview-id"

# Staging environment configuration
[[env.staging.d1_databases]]
binding = "DB"
database_name = "openai-api-staging"
database_id = "your-staging-d1-database-id"

[[env.staging.kv_namespaces]]
binding = "CACHE"
id = "your-staging-kv-namespace-id"
preview_id = "your-staging-kv-preview-id"

[[env.staging.kv_namespaces]]
binding = "RATE_LIMIT"
id = "your-staging-rate-limit-kv-id"
preview_id = "your-staging-rate-limit-preview-id"

# Production environment configuration
[[env.production.d1_databases]]
binding = "DB"
database_name = "openai-api-prod"
database_id = "your-prod-d1-database-id"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "your-prod-kv-namespace-id"
preview_id = "your-prod-kv-preview-id"

[[env.production.kv_namespaces]]
binding = "RATE_LIMIT"
id = "your-prod-rate-limit-kv-id"
preview_id = "your-prod-rate-limit-preview-id"

# Environment variables (these will be set via wrangler secrets)
[vars]
ALLOWED_ORIGINS = "http://localhost:3000,https://wemake.cx,https://staging.wemake.cx"
RATE_LIMIT_PER_MINUTE = "60"
MAX_TOKENS_DEFAULT = "4096"
DEFAULT_MODEL = "anthropic/claude-3.5-sonnet"

# Secrets (use 'wrangler secret put' to set these)
# OPENROUTER_API_KEY = set via wrangler secret
# POSTHOG_API_KEY = set via wrangler secret
# POSTHOG_HOST = set via wrangler secret

# Analytics and observability
[env.production.analytics_engine_datasets]
binding = "ANALYTICS"
dataset = "openai-api-analytics"

[env.staging.analytics_engine_datasets]
binding = "ANALYTICS"
dataset = "openai-api-analytics-staging"

# AI Gateway configuration (optional)
[env.production.ai]
binding = "AI"

[env.staging.ai]
binding = "AI"

[env.development.ai]
binding = "AI"