name = "frontpage"
compatibility_date = "2025-02-14"
compatibility_flags = ["nodejs_compat_v2"]
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "contact-submissions"
database_id = "e44ce62c-a835-49e8-b75c-4f20f7d520a7"

[[r2_buckets]]
binding = "WEMAKE_BUCKET"
bucket_name = "wemake"
