name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Deploy Website
        uses: cloudflare/wrangler-action@707f63750981584eb6abc365a50d441516fb04b8 # v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: apps/website
